# 数据源
spring:
  application:
    name: dept-demo
  datasource:
    url: jdbc:mariadb://10.0.0.11:3306/dept_test
    username: admin
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间


# mybatis配置
#mybatis:
#  mapper-locations: classpath:mapper/*.xml    # mapper映射文件位置
#  type-aliases-package: net.zfcloud.domain   # 实体类所在的位置
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: net.zfcloud.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
